### ISSUE TITLE
Script sometimes fails

### ISSUE THREAD

**Issue by khanrahan** [flamescripts/Flame_Scripts#2]
Hi hi!

Sporadically... this script will fail, but I have figured out why yet.  Screenshot below of failure output

![Screenshot at 2023-02-27 10-32-27-PT](https://user-images.githubusercontent.com/5342211/221610014-afab0bdd-0490-4ae1-8846-0a08bb98d7ec.jpg)

If I try xsetwacom in a separate shell, everything seems fine

```
xsetwacom --list
Wacom Intuos Pro L Pen stylus   	id: 11	type: STYLUS    
Wacom Intuos Pro L Pen eraser   	id: 12	type: ERASER    
Wacom Intuos Pro L Pen cursor   	id: 13	type: CURSOR    
Wacom Intuos Pro L Pad pad      	id: 14	type: PAD       
Wacom Intuos Pro L Finger touch 	id: 15	type: TOUCH     
```
 
I can usually sort it out by doing a couple Shift + T + Ins in Flame to reset the Wacom and then the CentOS Wacom fix script will work.

Will post any more I figure out.
Thanks in advance!

**Comment by khanrahan** [comment]
I should add... this is running the script as launcher menu item to run in the Terminal.

![Screenshot at 2023-02-27 13-52-52](https://user-images.githubusercontent.com/5342211/221656417-cf82d0ec-16fe-4992-b0d3-9b30d86872f3.png)

**Comment by flamescripts** [comment]
Have you tried w/ the full path for xsetwacom in the script.  may also need to export DISPLAY if using the launcher.  What version of CentOS, I'll try some tests.
